package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type Field struct {
	Name string
	Type string
	Tag  string
}

type Model struct {
	Name   string
	Fields []Field
}

var funcs = template.FuncMap{
	"toSnakeCase": toSnakeCase,
	"lowerFirst":  lowerFirst,
}

const requestTemplate = `// Code generated by gen-requests. DO NOT EDIT.

package handler

import (
	"time"

	"github.com/jinzhu/copier"
	"gorm.io/datatypes"

	"github.com/sssjuing/media-vault/internal/app/server/model"
)

{{range .}}
type {{.Name}}CreateRequest struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`json:\"{{toSnakeCase .Name}}\" validate:\"required\"`" + `
{{- end}}
}

type {{.Name}}UpdateRequest struct {
	ID uint ` + "`json:\"id\" validate:\"required\"`" + `
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`json:\"{{toSnakeCase .Name}}\"`" + `
{{- end}}
}

func (r *{{.Name}}CreateRequest) ToModel() *model.{{.Name}} {
	var m model.{{.Name}}
	_ = copier.Copy(&m, r)
	return &m
}

func (r *{{.Name}}UpdateRequest) UpdateModel(m *model.{{.Name}}) {
	_ = copier.Copy(m, r)
}

{{end}}
`

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 {
			if 'A' <= r && r <= 'Z' {
				prev := rune(s[i-1])
				if !('A' <= prev && prev <= 'Z') || (i+1 < len(s) && 'a' <= rune(s[i+1]) && rune(s[i+1]) <= 'z') {
					result.WriteRune('_')
				}
			}
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func parseModelFile(filename string) ([]Model, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var models []Model
	ast.Inspect(node, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}

		modelName := ts.Name.Name
		var fields []Field

		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				continue
			}

			fieldName := field.Names[0].Name
			if fieldName == "ID" || fieldName == "CreatedAt" || fieldName == "UpdatedAt" || fieldName == "DeletedAt" || fieldName == "BaseModel" {
				continue
			}

			fieldType := getTypeName(field.Type)
			if fieldType == "" {
				continue
			}

			fields = append(fields, Field{
				Name: fieldName,
				Type: fieldType,
			})
		}

		if len(fields) > 0 {
			models = append(models, Model{
				Name:   modelName,
				Fields: fields,
			})
		}

		return true
	})

	return models, nil
}

var basicTypes = map[string]bool{
	"string":  true,
	"int":     true,
	"int8":    true,
	"int16":   true,
	"int32":   true,
	"int64":   true,
	"uint":    true,
	"uint8":   true,
	"uint16":  true,
	"uint32":  true,
	"uint64":  true,
	"float32": true,
	"float64": true,
	"bool":    true,
	"byte":    true,
	"rune":    true,
}

func getTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		name := t.Name
		if !basicTypes[name] && name != "Time" && name != "JSON" && name != "JSONSlice" {
			return "model." + name
		}
		return name
	case *ast.StarExpr:
		inner := getTypeName(t.X)
		if inner != "" {
			return "*" + inner
		}
	case *ast.ArrayType:
		inner := getTypeName(t.Elt)
		if inner != "" {
			return "[]" + inner
		}
	case *ast.SelectorExpr:
		if x, ok := t.X.(*ast.Ident); ok {
			return x.Name + "." + t.Sel.Name
		}
	}
	return ""
}

func main() {
	output := flag.String("output", "", "Output file path")
	include := flag.String("include", "", "Comma-separated list of models to include")
	exclude := flag.String("exclude", "", "Comma-separated list of models to exclude")
	flag.Parse()

	if flag.NArg() == 0 {
		fmt.Println("Usage: gen-requests [options] <model-file>")
		flag.PrintDefaults()
		os.Exit(1)
	}

	modelFile := flag.Arg(0)
	models, err := parseModelFile(modelFile)
	if err != nil {
		fmt.Printf("Error parsing model file: %v\n", err)
		os.Exit(1)
	}

	if *include != "" {
		includes := strings.Split(*include, ",")
		includeMap := make(map[string]bool)
		for _, name := range includes {
			includeMap[strings.TrimSpace(name)] = true
		}
		var filtered []Model
		for _, m := range models {
			if includeMap[m.Name] {
				filtered = append(filtered, m)
			}
		}
		models = filtered
	}

	if *exclude != "" {
		excludes := strings.Split(*exclude, ",")
		excludeMap := make(map[string]bool)
		for _, name := range excludes {
			excludeMap[strings.TrimSpace(name)] = true
		}
		var filtered []Model
		for _, m := range models {
			if !excludeMap[m.Name] {
				filtered = append(filtered, m)
			}
		}
		models = filtered
	}

	tmpl, err := template.New("request").Funcs(funcs).Parse(requestTemplate)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
		os.Exit(1)
	}

	var outputFile *os.File
	if *output != "" {
		if err := os.MkdirAll(filepath.Dir(*output), 0755); err != nil {
			fmt.Printf("Error creating output directory: %v\n", err)
			os.Exit(1)
		}
		outputFile, err = os.Create(*output)
		if err != nil {
			fmt.Printf("Error creating output file: %v\n", err)
			os.Exit(1)
		}
		defer outputFile.Close()
	} else {
		outputFile = os.Stdout
	}

	if err := tmpl.Execute(outputFile, models); err != nil {
		fmt.Printf("Error executing template: %v\n", err)
		os.Exit(1)
	}
}
