// Code generated by gen-requests. DO NOT EDIT.

package handler

import (
	"time"

	"github.com/jinzhu/copier"

	"github.com/sssjuing/media-vault/internal/app/server/model"
)

type ActressCreateRequest struct {
	UniqueName string                  `json:"unique_name" validate:"required"`
	NameSets   []*model.ActressNameSet `json:"name_sets" validate:"required"`
	BirthDate  *time.Time              `json:"birth_date" validate:"required"`
	BirthPlace *string                 `json:"birth_place" validate:"required"`
	Height     *int                    `json:"height" validate:"required"`
	Weight     *int                    `json:"weight" validate:"required"`
	BWH        *model.BWH              `json:"bwh" validate:"required"`
	Cup        *string                 `json:"cup" validate:"required"`
	BloodGroup *string                 `json:"blood_group" validate:"required"`
	DebutDate  *time.Time              `json:"debut_date" validate:"required"`
	Hobbies    *string                 `json:"hobbies" validate:"required"`
	Notes      *string                 `json:"notes" validate:"required"`
}

type ActressUpdateRequest struct {
	ID         uint                    `json:"id" validate:"required"`
	UniqueName string                  `json:"unique_name"`
	NameSets   []*model.ActressNameSet `json:"name_sets"`
	BirthDate  *time.Time              `json:"birth_date"`
	BirthPlace *string                 `json:"birth_place"`
	Height     *int                    `json:"height"`
	Weight     *int                    `json:"weight"`
	BWH        *model.BWH              `json:"bwh"`
	Cup        *string                 `json:"cup"`
	BloodGroup *string                 `json:"blood_group"`
	DebutDate  *time.Time              `json:"debut_date"`
	Hobbies    *string                 `json:"hobbies"`
	Notes      *string                 `json:"notes"`
}

func (r *ActressCreateRequest) ToModel() *model.Actress {
	var m model.Actress
	_ = copier.Copy(&m, r)
	return &m
}

func (r *ActressUpdateRequest) UpdateModel(m *model.Actress) {
	_ = copier.Copy(m, r)
}
