// Code generated by gen-requests. DO NOT EDIT.

package handler

import (
	"time"

	"github.com/jinzhu/copier"
	"gorm.io/datatypes"

	"github.com/sssjuing/media-vault/internal/app/server/model"
)

type VideoCreateRequest struct {
	SerialNumber    string                  `json:"serial_number" validate:"required"`
	CoverPath       string                  `json:"cover_path" validate:"required"`
	Title           *string                 `json:"title" validate:"required"`
	ChineseTitle    *string                 `json:"chinese_title" validate:"required"`
	ActressNameSets []*model.ActressNameSet `json:"actress_name_sets" validate:"required"`
	ReleaseDate     *time.Time              `json:"release_date" validate:"required"`
	VideoPath       *string                 `json:"video_path" validate:"required"`
	Mosaic          *bool                   `json:"mosaic" validate:"required"`
	Tags            *datatypes.JSON         `json:"tags" validate:"required"`
	Synopsis        *string                 `json:"synopsis" validate:"required"`
	M3u8URL         *string                 `json:"m3u8_url" validate:"required"`
	M3u8Referer     *string                 `json:"m3u8_referer" validate:"required"`
}

type VideoUpdateRequest struct {
	ID              uint                    `json:"id" validate:"required"`
	SerialNumber    string                  `json:"serial_number"`
	CoverPath       string                  `json:"cover_path"`
	Title           *string                 `json:"title"`
	ChineseTitle    *string                 `json:"chinese_title"`
	ActressNameSets []*model.ActressNameSet `json:"actress_name_sets"`
	ReleaseDate     *time.Time              `json:"release_date"`
	VideoPath       *string                 `json:"video_path"`
	Mosaic          *bool                   `json:"mosaic"`
	Tags            *datatypes.JSON         `json:"tags"`
	Synopsis        *string                 `json:"synopsis"`
	M3u8URL         *string                 `json:"m3u8_url"`
	M3u8Referer     *string                 `json:"m3u8_referer"`
}

func (r *VideoCreateRequest) ToModel() *model.Video {
	var m model.Video
	_ = copier.Copy(&m, r)
	return &m
}

func (r *VideoUpdateRequest) UpdateModel(m *model.Video) {
	_ = copier.Copy(m, r)
}
